docker-build:
  image: hub.osell.com/base/docker-compose
  stage: build
  script:
    - docker-compose -f docker-compose-build.yml build
  rules:
    - exists:
        - docker-compose-build.yml
    - if: '$CI_COMMIT_BRANCH == "release"'

docker-push:
  image: hub.osell.com/base/docker-compose
  stage: deploy
  script:
    - docker-compose -f docker-compose-build.yml push
  rules:
    - exists:
        - docker-compose-build.yml
    - if: '$CI_COMMIT_BRANCH == "release"'
