# Use postgres/example user/password credentials

services:
  db:
    image: postgres:12.20-bookworm
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    env_file:
      - .env

  app:
    image: 0x5c0f/rzplan-backend:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./fonts:/app/app/rz/assets/fonts
    env_file:
      - .env
    depends_on:
      - db