"""add index to performance_data tables

Revision ID: 2e9baf336715
Revises: a78c2fafc84a
Create Date: 2024-10-08 17:20:15.834840

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e9baf336715'
down_revision = 'a78c2fafc84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_request_uri', 'performance_data', ['request_uri'])
    op.create_index('ix_created_at', 'performance_data', ['created_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_uri', table_name='performance_data')
    op.drop_index('ix_created_at', table_name='performance_data')
    # ### end Alembic commands ###
