"""Initial migration for performance tracking and data

Revision ID: a78c2fafc84a
Revises: 1a31ce608336
Create Date: 2024-09-29 13:24:04.126506

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a78c2fafc84a'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_tracking_config',
        sa.Column('tracking_domain', sa.String(length=191), nullable=False),
        sa.Column('tracking_code', sa.String(length=191), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tracking_code'),
        sa.UniqueConstraint('tracking_domain')
    )
    
    op.create_table('performance_data',
        sa.Column('dns_time', sa.Float(), nullable=True),
        sa.Column('redirect_time', sa.Float(), nullable=True),
        sa.Column('dom_load_time', sa.Float(), nullable=True),
        sa.Column('frontend_performance', sa.Float(), nullable=True),
        sa.Column('ttfb_time', sa.Float(), nullable=True),
        sa.Column('content_load_time', sa.Float(), nullable=True),
        sa.Column('onload_callback_time', sa.Float(), nullable=True),
        sa.Column('dns_cache_time', sa.Float(), nullable=True),
        sa.Column('unload_time', sa.Float(), nullable=True),
        sa.Column('tcp_handshake_time', sa.Float(), nullable=True),
        sa.Column('request_uri', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('tracking_domain', sa.String(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['tracking_domain'], ['performance_tracking_config.tracking_domain'], ),
        sa.PrimaryKeyConstraint('id')
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_data')
    op.drop_table('performance_tracking_config')
    # ### end Alembic commands ###
